export const REGISTER = 'REGISTER';
export const DATA_REQUEST = 'DATA_REQUEST';
export const DATA_RESPONSE = 'DATA_RESPONSE';
export const REQUEST_SUCCEEDED = 'REQUEST_SUCCEEDED';
export const REQUEST_FAILED = 'REQUEST_FAILED';
export const UPDATE_STATE = 'UPDATE_STATE';
export const STATE_UPDATED = 'STATE_UPDATED';