export const SET_COMMUNICATOR = 'SET_COMMUNICATOR';
export const HANDLE_MOVE_PIECE = 'HANDLE_MOVE_PIECE';
export const HANDLE_DRAG_PIECE = 'HANDLE_DRAG_PIECE';
export const SET_BOARD_STATE = 'SET_BOARD_STATE';