export const SET_SOURCE_WINDOW = 'SET_SOURCE_WINDOW';
export const SET_TEXT = 'SET_TEXT';
export const TOKEN_REQUEST = 'TOKEN_REQUEST';
export const TOKEN_RESPONSE = 'TOKEN_RESPONSE';
export const FETCH_TOKEN_FAILED = 'FETCH_TOKEN_FAILED';