export const SET_SOURCE_WINDOW = 'SET_SOURCE_WINDOW';
export const TOKEN_REQUEST = 'TOKEN_REQUEST';
export const TOKEN_RESPONSE = 'TOKEN_RESPONSE';
export const FETCH_TOKEN_FAILED = 'FETCH_TOKEN_FAILED';
export const HANDLE_MOVE_PIECE = 'HANDLE_MOVE_PIECE';
export const HANDLE_DRAG_PIECE = 'HANDLE_DRAG_PIECE';
export const SET_BOARD_STATE = 'SET_BOARD_STATE';