export const SET_IFRAME_LOADED = 'SET_IFRAME_LOADED';
export const STATE_REQUEST = 'STATE_REQUEST';
export const STATE_RESPONSE = 'STATE_RESPONSE';
export const FETCH_STATE_FAILED = 'FETCH_STATE_FAILED';
export const POST_STATE_FAILED = 'POST_STATE_FAILED';