export const SELECT_IFRAME = 'SELECT_IFRAME';
export const SET_IFRAME_LOADED = 'SET_IFRAME_LOADED';
export const TEXT_REQUEST = 'TEXT_REQUEST';
export const TEXT_RESPONSE = 'TEXT_RESPONSE';
export const FETCH_TEXT_FAILED = 'FETCH_TEXT_FAILED';
export const POST_TEXT_FAILED = 'POST_TEXT_FAILED';