export const ASSIGN_IFRAME = 'ASSIGN_IFRAME';
export const SET_IFRAME_LOADED = 'SET_IFRAME_LOADED';
export const API_REQUEST = 'API_REQUEST';
export const API_REQUEST_SUCCESS = 'API_REQUEST_SUCCESS';
export const API_REQUEST_FAILED = 'API_REQUEST_FAILED';